; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = watch

[env:watch]
platform = ststm32
board = epaper_smart_watch
framework = arduino
upload_protocol = dfu
monitor_speed = 115200
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D HAL_TSC_MODULE_ENABLED
    -D USB_MANUFACTURER="OpenEPaperLink"
    -D USB_PRODUCT="E-paper Smart Watch Bring-up"

[env:watch_stlink]
extends = env:watch
upload_protocol = stlink
