// Generated by code/tools/generate_ui_assets.py. Do not edit by hand.
#pragma once

#include <Arduino.h>

struct BitmapGlyph {
  uint32_t bitmap_offset;
  uint8_t width;
  uint8_t height;
  int8_t x_offset;
  int8_t y_offset;
  uint8_t x_advance;
};

struct BitmapFont {
  const uint8_t* bitmap;
  const BitmapGlyph* glyphs;
  uint8_t first_character;
  uint8_t last_character;
  uint8_t pixel_size;
  uint8_t ascent;
  uint8_t descent;
};

enum class WatchIcon : uint8_t {
  Notifications,
  Timer,
  Alarms,
  Music,
  Weather,
  Sensors,
  Activity,
  Settings,
  Bluetooth,
  Battery,
  Count,
};

struct BitmapIcon {
  uint32_t bitmap_offset;
  uint8_t width;
  uint8_t height;
};

namespace WatchAssets {
extern const BitmapFont Ui16;
extern const BitmapFont Bold22;
extern const BitmapFont Bold36;
extern const BitmapFont Clock64;

const BitmapIcon& icon(WatchIcon icon, uint8_t size);
const uint8_t* iconBitmap();
}  // namespace WatchAssets
