[platformio]
boards_dir = ../boards

[env:watch_dfu_bootloader]
platform = ststm32
board = epaper_smart_watch
framework = arduino
upload_protocol = dfu
board_upload.maximum_size = 65536
build_flags =
    -D HAL_PCD_MODULE_ENABLED
    -D USBD_DFU_APP_DEFAULT_ADD=0x08010000U

[env:watch_dfu_bootloader_stlink]
extends = env:watch_dfu_bootloader
upload_protocol = stlink
