"""Generate 1-bit firmware fonts and icons from the checked-in source assets.

Run from the repository root with Python 3 after installing Pillow and CairoSVG:
    python code/tools/generate_ui_assets.py

The generated C++ is checked in, so these Python packages are not build-time
dependencies for PlatformIO.
"""

from __future__ import annotations

import io
from pathlib import Path

import cairosvg
from PIL import Image, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "assets" / "fonts"
ICON_DIR = ROOT / "assets" / "icons"
HEADER = ROOT / "include" / "watch_assets.h"
SOURCE = ROOT / "src" / "watch_assets.cpp"
FIRST = 32
LAST = 126

FONT_SPECS = [
    ("Ui16", "AtkinsonHyperlegibleNext-Regular.ttf", 16),
    ("Bold22", "AtkinsonHyperlegibleNext-ExtraBold.ttf", 22),
    ("Bold36", "AtkinsonHyperlegibleNext-ExtraBold.ttf", 36),
    ("Clock64", "AtkinsonHyperlegibleNext-ExtraBold.ttf", 64),
]

ICON_NAMES = [
    "message-circle",
    "timer",
    "alarm-clock",
    "music",
    "cloud-sun",
    "gauge",
    "activity",
    "settings",
    "bluetooth",
    "battery-medium",
]


def cpp_bytes(values: list[int], indent: str = "    ") -> str:
    if not values:
        return indent + "0x00,"
    lines = []
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        lines.append(indent + ", ".join(f"0x{x:02X}" for x in chunk) + ",")
    return "\n".join(lines)


def pack_image(image: Image.Image) -> list[int]:
    mono = image.convert("L")
    width, height = mono.size
    packed: list[int] = []
    for y in range(height):
        for byte_x in range((width + 7) // 8):
            value = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < width and mono.getpixel((x, y)) >= 128:
                    value |= 0x80 >> bit
            packed.append(value)
    return packed


def render_font(symbol: str, filename: str, size: int):
    font = ImageFont.truetype(str(FONT_DIR / filename), size)
    ascent, descent = font.getmetrics()
    glyphs = []
    bitmap: list[int] = []
    for codepoint in range(FIRST, LAST + 1):
        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width = max(0, right - left)
        height = max(0, bottom - top)
        offset = len(bitmap)
        if width and height:
            image = Image.new("L", (width, height), 0)
            from PIL import ImageDraw

            ImageDraw.Draw(image).text(
                (-left, -top), character, font=font, fill=255, anchor="ls"
            )
            bitmap.extend(pack_image(image))
        advance = max(1, round(font.getlength(character)))
        glyphs.append((offset, width, height, left, top, advance))
    return symbol, size, ascent, descent, glyphs, bitmap


def render_icon(name: str, size: int) -> Image.Image:
    svg = (ICON_DIR / f"{name}.svg").read_bytes()
    png = cairosvg.svg2png(
        bytestring=svg,
        output_width=size * 4,
        output_height=size * 4,
    )
    image = Image.open(io.BytesIO(png)).convert("RGBA")
    alpha = image.getchannel("A")
    alpha = alpha.resize((size, size), Image.Resampling.LANCZOS)
    return alpha.point(lambda value: 255 if value >= 72 else 0)


def main() -> None:
    fonts = [render_font(*spec) for spec in FONT_SPECS]
    icons = []
    icon_bitmap: list[int] = []
    for name in ICON_NAMES:
        for size in (16, 28):
            offset = len(icon_bitmap)
            icon_bitmap.extend(pack_image(render_icon(name, size)))
            icons.append((name, size, offset))

    header = """// Generated by code/tools/generate_ui_assets.py. Do not edit by hand.
#pragma once

#include <Arduino.h>

struct BitmapGlyph {
  uint32_t bitmap_offset;
  uint8_t width;
  uint8_t height;
  int8_t x_offset;
  int8_t y_offset;
  uint8_t x_advance;
};

struct BitmapFont {
  const uint8_t* bitmap;
  const BitmapGlyph* glyphs;
  uint8_t first_character;
  uint8_t last_character;
  uint8_t pixel_size;
  uint8_t ascent;
  uint8_t descent;
};

enum class WatchIcon : uint8_t {
  Notifications,
  Timer,
  Alarms,
  Music,
  Weather,
  Sensors,
  Activity,
  Settings,
  Bluetooth,
  Battery,
  Count,
};

struct BitmapIcon {
  uint32_t bitmap_offset;
  uint8_t width;
  uint8_t height;
};

namespace WatchAssets {
"""
    for symbol, *_ in fonts:
        header += f"extern const BitmapFont {symbol};\n"
    header += """
const BitmapIcon& icon(WatchIcon icon, uint8_t size);
const uint8_t* iconBitmap();
}  // namespace WatchAssets
"""

    source = """// Generated by code/tools/generate_ui_assets.py. Do not edit by hand.
#include "watch_assets.h"

namespace {
"""
    for symbol, size, ascent, descent, glyphs, bitmap in fonts:
        source += f"\nconstexpr uint8_t {symbol}_BITMAP[] = {{\n{cpp_bytes(bitmap)}\n}};\n"
        source += f"constexpr BitmapGlyph {symbol}_GLYPHS[] = {{\n"
        for offset, width, height, left, top, advance in glyphs:
            source += (
                f"    {{{offset}, {width}, {height}, {left}, {top}, {advance}}},\n"
            )
        source += "};\n"
    source += f"\nconstexpr uint8_t ICON_BITMAP[] = {{\n{cpp_bytes(icon_bitmap)}\n}};\n"
    source += "constexpr BitmapIcon ICONS_16[] = {\n"
    for _, size, offset in icons:
        if size == 16:
            source += f"    {{{offset}, 16, 16}},\n"
    source += "};\nconstexpr BitmapIcon ICONS_28[] = {\n"
    for _, size, offset in icons:
        if size == 28:
            source += f"    {{{offset}, 28, 28}},\n"
    source += "};\n\n}  // namespace\n\nnamespace WatchAssets {\n"
    for symbol, size, ascent, descent, *_ in fonts:
        source += (
            f"const BitmapFont {symbol} = {{{symbol}_BITMAP, {symbol}_GLYPHS, "
            f"{FIRST}, {LAST}, {size}, {ascent}, {descent}}};\n"
        )
    source += """

const BitmapIcon& icon(WatchIcon value, uint8_t size) {
  const uint8_t index = static_cast<uint8_t>(value);
  return size <= 16 ? ICONS_16[index] : ICONS_28[index];
}

const uint8_t* iconBitmap() {
  return ICON_BITMAP;
}
}  // namespace WatchAssets
"""

    HEADER.write_text(header, encoding="utf-8", newline="\n")
    SOURCE.write_text(source, encoding="utf-8", newline="\n")
    print(f"Generated {HEADER.relative_to(ROOT)} and {SOURCE.relative_to(ROOT)}")
    print(f"Font bitmaps: {sum(len(font[-1]) for font in fonts):,} bytes")
    print(f"Icon bitmaps: {len(icon_bitmap):,} bytes")


if __name__ == "__main__":
    main()
